### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by groggemans** [holms/ansible-fqdn#17]
Would you mind to start versioning the role and add tags? I would like to pin a specific version in my common setup role.

(absolutely necessary in a production environment)

**Comment by holms** [comment]
If you'll demonstrate me couple of repositories from ansible-galaxy where they are tagging their roles, then I'll do as they do :)

**Comment by groggemans** [comment]
It's done by most people, to name a few;
https://galaxy.ansible.com/geerlingguy/
https://galaxy.ansible.com/andrewrothstein/
https://galaxy.ansible.com/tersmitten/

All there roles have versions/tags.

**Comment by holms** [comment]
Done :)

**Comment by groggemans** [comment]
Thank you!

ps: don't forget to re-import in galaxy
