### ISSUE TITLE
Lineinfile misses pre-existing /etc/hosts entry

### ISSUE THREAD

**Issue by ceribik** [holms/ansible-fqdn#18]
As per the title. tasks/linux.cf needs the following change:

> lineinfile: dest=/etc/hosts line='{{ ansible_default_ipv4.address }} {{ fqdn }} {{ inventory_hostname_short }}' state=present backup=yes

should be

> lineinfile: dest=/etc/hosts regexp='^{{ ansible_default_ipv4.address }}' line='{{ ansible_default_ipv4.address }} {{ fqdn }} {{ inventory_hostname_short }}' state=present backup=yes

If this is not done, a prexisting hosts entry (at first run) will take precedence over the line that ansible adds.

**Comment by holms** [comment]
Can you do pull request and test this :)?

-----Original Message-----

**Comment by holms** [comment]
is this still applicable?
