### ISSUE TITLE
add handler to avoid to always bounce the service

### ISSUE THREAD

**Issue by roumano** [holms/ansible-fqdn#24]
on need task in linux.yml i will recommand to use :
   notify:      - restart hostname

and create a handlers :  main.yml
- name: restart hostname
  service: name=hostname state=restarted
  async: 45
  poll: 0
  when: ansible_distribution not in [ 'RedHat', 'CentOS' ]

It's will avoid to always bounce the service and the final state result will be better ;) 

What do you think ?

**Comment by holms** [comment]
@roumano test it, and make pull request if it works :)

**Comment by roumano** [comment]
Hi,

Sadly actually i only use ansible_os_family == "RedHat"  so i can't really test it
feel free to close the issue or someone can test it ?
