### ISSUE TITLE
debian 8.6

### ISSUE THREAD

**Issue by roumano** [holms/ansible-fqdn#28]
on the Debian Jessie the task restart hostname failed : 

TASK [ansible-fqdn : restart hostname] *****************************************
fatal: [debian]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service hostname: Failed to restart hostname.service: Unit hostname.service is masked.\n"}

On the box, it's like this :  

root@test:~# systemctl status hostname
● hostname.service
   Loaded: masked (/dev/null)
   Active: inactive (dead)

**Comment by tersmitten** [comment]
Same story for Ubuntu 16.04, both use `systemd`

**Comment by roumano** [comment]
not sure if it's can help but personnaly, on other ansible task i use this conditonnal test to known if it's a  systemd machine :  
when: ansible_service_mgr == 'systemd'
