### ISSUE TITLE
printing correct entries in /etc/hosts

### ISSUE THREAD

**Issue by ksingh7** [holms/ansible-fqdn#3]
Hi , to get correct value in /etc/hosts you should use ``` {{ hostvars[item].ansible_hostname }}.{{ fqdn }} ```

it will print in /etc/hosts as

``` 10.188.0.47 one.csc.fi one ```  ( IP FQDN HOSTNAME )

use below in default.yml

```
  lineinfile: dest=/etc/hosts regexp='{{ hostvars[item].ansible_hostname }}$' line='{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}.{{ fqdn }} {{ item }}' state=present backup=yes
```

**Comment by holms** [comment]
Can you do pull request? as far as I remember I've tried your method once, it wasn't working on debian I think, or in RHEL... when I did like it does now, it started to work.

**Comment by hut8** [comment]
The way it's done now in this role doesn't seem to work on Debian:

```
% cat /etc/hosts 
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
216.120.248.265 staging  staging.example.com
% hostname
staging
% hostname --fqdn
staging
```

This causes issues with mail (among other things). Of course I changed my server's address and hostname in the example.
