### ISSUE TITLE
Improve .travis.yml

### ISSUE THREAD

**Issue by tersmitten** [holms/ansible-fqdn#31]
Having a `.travis.yml` file like [this one](https://github.com/Oefenweb/ansible-komodo-ide/blob/master/.travis.yml) makes testing a accepting pull request more easy. You can also specify [versions](https://github.com/Oefenweb/ansible-dropbox/blob/master/.travis.yml) that are know to fail (due to bugs).

Do you want me to add something similar?

**Comment by holms** [comment]
@tersmitten this would be wonderfull. Now travis tests are failing.

**Comment by tersmitten** [comment]
I'll modify the existing one

**Comment by tersmitten** [comment]
Is the a reason that service networkingin is async, instead of a handler?

#23

**Comment by holms** [comment]
@tersmitten I don't remember why I haven't used handler, there was some problem with it back then. Try normal approach, if you find handlers are working, then let's use them

**Comment by tersmitten** [comment]
I'll give it a try.

**Comment by holms** [comment]
@tersmitten if you have more time, i have some interesting ansible books which you can also contirbute to. Half of them not even on ansible galaxy, and do not have travis :) If you find them interesting would be really nice to have you there :}

**Comment by tersmitten** [comment]
On Github?

**Comment by holms** [comment]
Yes in my profile :)
