### ISSUE TITLE
Reasonable defaults

### ISSUE THREAD

**Issue by hut8** [holms/ansible-fqdn#8]
Right now you specify both the FQDN and the hostname in the playbook. But for all of my cases, I just need this:

```yaml
    - { role: holms.fqdn, fqdn: "{{ inventory_hostname }}", hostname: "{{ inventory_hostname_short }}" }
```

What about making that a default? Thoughts are appreciated.

**Comment by holms** [comment]
feel free to do a PR :)

**Comment by johnjelinek** [comment]
@hut8: this would prolly fix #10

**Comment by hut8** [comment]
@johnjelinek Actually I don't think so. I'll give the reason why in #10 -- the reason I say so is because that's exactly what I'm doing in my playbook right now :smile:

**Comment by holms** [comment]
I hope you're add a feature to update all hosts files in certain groups. This is the only way to avoid using DNS :) And I've needed this so much back then :)
